services:
  - type: web
    name: brainpulse-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd idp && npm install && npm run build && mkdir -p ../backend/static && cp -r dist/* ../backend/static && cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
